# Generated by Django 5.0.3 on 2024-04-02 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "tavg",
                    models.IntegerField(null=True, verbose_name="Average Temp (°F)"),
                ),
                ("tmax", models.IntegerField(verbose_name="Max Temp (°F)")),
                ("tmin", models.IntegerField(verbose_name="Min Temp (°F)")),
                ("prcp", models.FloatField(verbose_name="Precipitation (in)")),
                ("snow", models.FloatField(null=True, verbose_name="Snow (in)")),
                ("snwd", models.FloatField(null=True, verbose_name="Snow Depth (in)")),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="weather.station",
                    ),
                ),
            ],
        ),
    ]
