language: python
python:
 - "2.7"
 - "3.4"
 - "pypy"
env:
 - DJANGO="django==1.6" REST="djangorestframework==2.3.14" PANDAS="pandas==0.14.1"
install:
 - pip install $DJANGO
 - pip install $REST
 - pip install $PANDAS
script:
 - python setup.py test
