language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
env:
  matrix:
    - DJANGO="django==1.8.11" REST="djangorestframework==3.3.3"
    - DJANGO="django==1.9.4" REST="djangorestframework==3.3.3"
    - DJANGO="django==1.9.4" REST="djangorestframework==3.3.3" LINT=1
  global:
    - PANDAS="pandas>=0.18"
install:
 - pip install $DJANGO
 - pip install $REST
 - pip install $PANDAS
 - pip install flake8
script:
 - ./runtests.sh
